# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d98b4e9a1005ac06659ed311ec13b113cf66b671c698b9d0914f5145da11f480cd4995dac4c669e04a07677710b2052f29dcf544b4c946e2df6e36c7490a9f

test:
  secret_key_base: 3b5497521f2dcfaac34b0366ff15878ad1fa23d4f993f909a8a72ddba9ce9508fc7264af94e972756fddda1e6917b5274b8b3cb00aae6ed9f36af500cfa083ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
